name: Build RPM and DEB Packages

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install RPM build tools
        run: sudo apt-get install -y rpm

      - name: Setup RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp count_files.sh ~/rpmbuild/SOURCES/
          cp count-files.spec ~/rpmbuild/SPECS/

      - name: Build RPM
        run: rpmbuild -ba ~/rpmbuild/SPECS/count-files.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ~/rpmbuild/RPMS/**/*.rpm

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup DEB build environment
        run: |
          mkdir -p count-files-1.0/DEBIAN
          mkdir -p count-files-1.0/usr/local/bin
          cp count_files.sh count-files-1.0/usr/local/bin/
          chmod 755 count-files-1.0/usr/local/bin/count_files.sh
          echo "Package: count-files" > count-files-1.0/DEBIAN/control
          echo "Version: 1.0" >> count-files-1.0/DEBIAN/control
          echo "Section: base" >> count-files-1.0/DEBIAN/control
          echo "Priority: optional" >> count-files-1.0/DEBIAN/control
          echo "Architecture: all" >> count-files-1.0/DEBIAN/control
          echo "Maintainer: Pavlo Derkach <pawel.a.derckach@gmail.com>" >> count-files-1.0/DEBIAN/control
          echo "Description: Script to count files in /etc" >> count-files-1.0/DEBIAN/control
          echo " A simple Bash script that counts the number of regular files in the /etc directory." >> count-files-1.0/DEBIAN/control

      - name: Build DEB package
        run: dpkg-deb --build count-files-1.0

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ./count-files-1.0.deb
